#This is a global config file for the server.

#openai configuation
api_key:
  "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"
model:
  "gpt-4-1106-preview"
max_tokens:
  4096
proxy:
  "socks5://127.0.0.1:12777"