#This is a global config file for the server.

#openai configuation
api_key:
  "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"
model:
  "gpt-4-1106-preview"
max_tokens:
  4096
proxy:
  "socks5://127.0.0.1:12777"